# This is a basic workflow to help you get started with Actions

name: run

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: Pip install requests
      run: |
        sudo python -m pip install --upgrade --force pip 
        sudo pip install setuptools==33.1.1
        pip3 install requests
        pip3 install bs4
        pip3 install tqdm      
         
    - name: HealthCheckin
      run: |
        python3 index.py <<EOF
        
        EOF
        
